<a href="https://colab.research.google.com/github/Kure18/DSN_Mentorship/blob/main/Electric_Vehicle_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [3]:
EV_trimmed = pd.read_csv('/content/drive/MyDrive/MentorShip/Electric_Vehicle_Population_Size_History_By_County.csv',nrows=5000)

In [4]:
EV = pd.read_csv('/content/drive/MyDrive/MentorShip/Electric_Vehicle_Population_Size_History_By_County.csv')

In [5]:
EV_trimmed['Date'].fillna(EV_trimmed['Date'].mode()[0],inplace=True)
EV_trimmed['County'].fillna(EV_trimmed['County'].mode()[0],inplace=True)
EV_trimmed['State'].fillna(EV_trimmed['State'].mode()[0],inplace=True)

/tmp/ipykernel_3844/3381024864.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  EV_trimmed['Date'].fillna(EV_trimmed['Date'].mode()[0],inplace=True)
/tmp/ipykernel_3844/3381024864.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  EV_trimmed['County'].fillna(EV_trimmed['County'].mode()[0],inplace=True)
/tmp/ipykernel_3844/3381024864.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  EV_trimmed['State'].fillna(EV_trimmed['State'].mode()[0],inplace=True)

In [6]:
from sklearn.preprocessing import LabelEncoder
le_date = LabelEncoder()
le_county = LabelEncoder()
le_state = LabelEncoder()
le_vehicle = LabelEncoder()

In [7]:
EV_trimmed['Date'] = le_date.fit_transform(EV_trimmed['Date'])
EV_trimmed['County'] = le_county.fit_transform(EV_trimmed['County'])
EV_trimmed['State'] = le_state.fit_transform(EV_trimmed['State'])
EV_trimmed['Vehicle Primary Use'] = le_vehicle.fit_transform(EV_trimmed['Vehicle Primary Use'])

In [9]:
X = EV_trimmed.drop(columns='Percent Electric Vehicles')
y = EV_trimmed['Percent Electric Vehicles']

In [11]:
EV_trimmed["Success Threshold"] = EV_trimmed["Percent Electric Vehicles"]>0.6

In [12]:
EV_trimmed['Success Threshold']

0        True
1        True
2        True
3        True
4        True
        ...
4995     True
4996    False
4997     True
4998     True
4999    False
Name: Success Threshold, Length: 5000, dtype: bool

In [13]:
EV_trimmed.head()

,Date,County,State,Vehicle Primary Use,Battery Electric Vehicles (BEVs),Plug-In Hybrid Electric Vehicles (PHEVs),Electric Vehicle (EV) Total,Non-Electric Vehicle Total,Total Vehicles,Percent Electric Vehicles,Success Threshold
0,44,281,25,0,3,0,3,130,133,2.26,True
1,57,239,20,0,1,0,1,40,41,2.44,True
2,112,210,45,0,1,0,1,10,11,9.09,True
3,60,202,3,0,8,9,17,1775,1792,0.95,True
4,25,288,10,0,0,2,2,83,85,2.35,True

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [15]:
from sklearn.preprocessing import LabelEncoder
le_date = LabelEncoder()
le_state = LabelEncoder()
le_county = LabelEncoder()
le_vehicle = LabelEncoder()
le_success = LabelEncoder()

In [17]:
EV_trimmed["date"] = le_date.fit_transform(EV_trimmed['Date'])
EV_trimmed["county"] = le_county.fit_transform(EV_trimmed['County'])
EV_trimmed["state"] = le_state.fit_transform(EV_trimmed['State'])
EV_trimmed["vehicle"] = le_vehicle.fit_transform(EV_trimmed['Vehicle Primary Use'])
EV_trimmed["success"] = le_success.fit_transform(EV_trimmed['Success Threshold'])

In [18]:
X = EV_trimmed.drop(columns=['Success Threshold', 'Date', 'County', 'State', 'Vehicle Primary Use', 'Percent Electric Vehicles', 'success'])
y = EV_trimmed['Success Threshold']

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
X.shape

(5000, 9)

In [21]:
y.shape

(5000,)

In [22]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)
logistic_predictions = logistic_model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [23]:
logistic_predictions

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True, False,
        True, False,  True, False,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True,  True, False,  True,  True, False,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
        True, False,  True,  True,  True,  True, False, False,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True, False,  True, False,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False, False,  True, False,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False, False, False,  True,  True, False,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True, False,  True, False, False,  True,
       False, False, False, False,  True, False,  True,  True, False,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True, False,
        True, False, False, False,  True,  True,  True,  True, False,
        True, False, False, False,  True, False, False, False, False,
        True,  True, False,  True, False,  True, False,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True, False,  True,  True,  True, False,  True,  True,  True,
       False,  True, False, False, False,  True,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
        True,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True, False,  True,  True, False, False,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True, False, False, False,  True,  True,
        True,  True,  True, False,  True, False, False,  True,  True,
        True, False,  True, False,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True, False, False,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True, False, False,  True, False,  True, False,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True, False,  True, False,  True,  True,  True, False, False,
       False,  True,  True, False,  True, False, False,  True, False,
        True, False,  True,  True,  True,  True, False, False, False,
        True, False,  True,  True,  True,  True, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False, False,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False, False,  True,  True,  True,
        True,  True, False, False, False,  True, False,  True, False,
        True])

In [24]:
decision_tree_model = DecisionTreeClassifier()
decision_tree_model.fit(X_train,y_train)
decision_tree_predictions = decision_tree_model.predict(X_test)

In [25]:
metrics = {
    "Accuracy" : accuracy_score,
    "Precision" : precision_score,
    "Recall" : recall_score,
    "F1 Score" : f1_score
}

results = {}
for name,func in metrics.items():
  logistic_score = func(y_test,logistic_predictions)
  decision_tree_score = func(y_test,decision_tree_predictions)

  results[name] = {
      "Logistic Regression" : logistic_score,
      "Decision Tree" : decision_tree_score
  }

In [26]:
results

{'Accuracy': {'Logistic Regression': 0.999, 'Decision Tree': 0.989},
 'Precision': {'Logistic Regression': 0.9986111111111111,
  'Decision Tree': 0.9916666666666667},
 'Recall': {'Logistic Regression': 1.0, 'Decision Tree': 0.9930458970792768},
 'F1 Score': {'Logistic Regression': 0.9993050729673384,
  'Decision Tree': 0.9923558026407228}}

In [27]:
EV["Success Threshold"] = EV["Percent Electric Vehicles"]>0.6

In [28]:
EV['Success Threshold']

0        True
1        True
2        True
3        True
4        True
         ...
34666    True
34667    True
34668    True
34669    True
34670    True
Name: Success Threshold, Length: 34671, dtype: bool

In [29]:
EV.head()

,Date,County,State,Vehicle Primary Use,Battery Electric Vehicles (BEVs),Plug-In Hybrid Electric Vehicles (PHEVs),Electric Vehicle (EV) Total,Non-Electric Vehicle Total,Total Vehicles,Percent Electric Vehicles,Success Threshold
0,January 31 2023,Pulaski,MO,Passenger,3,0,3,130,133,2.26,True
1,June 30 2017,Norfolk,MA,Passenger,1,0,1,40,41,2.44,True
2,September 30 2025,Medina,TX,Passenger,1,0,1,10,11,9.09,True
3,June 30 2020,Maricopa,AZ,Passenger,8,9,17,1775,1792,0.95,True
4,December 31 2023,Richmond,GA,Passenger,0,2,2,83,85,2.35,True

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [31]:
from sklearn.preprocessing import LabelEncoder
le_date = LabelEncoder()
le_state = LabelEncoder()
le_county = LabelEncoder()
le_vehicle = LabelEncoder()
le_success = LabelEncoder()

In [32]:
EV["date"] = le_date.fit_transform(EV['Date'])
EV["county"] = le_county.fit_transform(EV['County'])
EV["state"] = le_state.fit_transform(EV['State'])
EV["vehicle"] = le_vehicle.fit_transform(EV['Vehicle Primary Use'])
EV["success"] = le_success.fit_transform(EV['Success Threshold'])

In [33]:
X = EV.drop(columns=['Success Threshold', 'Date', 'County', 'State', 'Vehicle Primary Use', 'Percent Electric Vehicles', 'success'])
y = EV['Success Threshold']

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [35]:
X.shape

(34671, 9)

In [36]:
y.shape

(34671,)

In [37]:
logistic_model = LogisticRegression()
logistic_model.fit(X_train,y_train)
logistic_predictions = logistic_model.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [38]:
logistic_predictions

array([ True, False, False, ...,  True,  True, False])

In [39]:
decision_tree_model = DecisionTreeClassifier()
decision_tree_model.fit(X_train,y_train)
decision_tree_predictions = decision_tree_model.predict(X_test)

In [40]:
metrics = {
    "Accuracy" : accuracy_score,
    "Precision" : precision_score,
    "Recall" : recall_score,
    "F1 Score" : f1_score
}

results = {}
for name,func in metrics.items():
  logistic_score = func(y_test,logistic_predictions)
  decision_tree_score = func(y_test,decision_tree_predictions)

  results[name] = {
      "Logistic Regression" : logistic_score,
      "Decision Tree" : decision_tree_score
  }

In [41]:
results

{'Accuracy': {'Logistic Regression': 0.9936553713049747,
  'Decision Tree': 0.9966834895457822},
 'Precision': {'Logistic Regression': 0.9923033602402853,
  'Decision Tree': 0.9977315689981097},
 'Recall': {'Logistic Regression': 0.9994327850255247,
  'Decision Tree': 0.9979202117602571},
 'F1 Score': {'Logistic Regression': 0.9958553127354935,
  'Decision Tree': 0.9978258814632763}}